export const AFFILIATE_LINKS = {
    highlevel: "https://www.gohighlevel.com/?fp_ref=yochay28",
    keap: "https://get.keap.com/8ez2ygxyejz5",
    centripe: "https://centripe.com/ref/your_id",
    capsule: "https://capsulecrm.com/?ref=your_id",
    hubspot: "https://www.hubspot.com/?aff=12345",
    salesforce: "https://www.salesforce.com/?aff=12345",
    zoho: "https://www.zoho.com/crm/?ref=12345",
    pipedrive: "https://www.pipedrive.com/?aff=12345",
    freshsales: "https://www.freshworks.com/crm/?aff=12345",
    "monday-crm": "https://www.monday.com/crm/?aff=12345",
    insightly: "https://www.insightly.com/?aff=12345",
    copper: "https://www.copper.com/?aff=12345",
    nimble: "https://www.nimble.com/?aff=12345",
    agile: "https://www.agilecrm.com/?aff=12345",
    nutshell: "https://www.nutshell.com/?aff=12345",
    close: "https://www.close.com/?aff=12345",
    "less-annoying": "https://www.lessannoyingcrm.com/?aff=12345",
    streak: "https://www.streak.com/?aff=12345",
    vtiger: "https://www.vtiger.com/?aff=12345",
    sugarcrm: "https://www.sugarcrm.com/?aff=12345",
    bitrix24: "https://www.bitrix24.com/?aff=12345",
    zendesk: "https://www.zendesk.com/sell/?aff=12345",
    engagebay: "https://www.engagebay.com/?aff=12345",
    crmone: "https://www.crmone.com/?aff=12345",
  };